### PR TITLE
A variety of improvements

### PR DESCRIPTION
**Pull request by bil-bas**
Network
Animations
Sound control

### CODE REVIEW

**Comment by ippa** [comment]
Cleaning up old pull-requests, I think we fixed this?

**Comment by bil-bas** [comment]
Nope; I'm not sure what you mean by "fixed". The thing is that the description "network tests" referred to the original pull request, but since then I added a dozen more commits (I probably should have updated the title of the request). If you look at the network, none of these have been merged into ippa/chingu _looks confused_

**Comment by ippa** [comment]
hm, assumed it was old stuff cause of the date :). I'll reopen and try to merge.

**Comment by bil-bas** [comment]
It was old, but I pushed it just as you were losing interest and jumping ship to HTML5, so I gave up on it :D Hadn't noticed you starting to merge again recently!

**Comment by ippa** [comment]
"This pull request cannot be automatically merged." .. gotta do this badboy manually it seems.

**Comment by bil-bas** [comment]
I guess it is up to me, eh? :(

**Comment by ippa** [comment]
heh, not your responsibillity. maybe part of the patch will be very hard to merge and has to be skipped though, we'll see.

**Comment by bil-bas** [comment]
Merged and rewrote the merged bit so the code is a bit nicer (and added tests because it was getting complex :) )

**Comment by ippa** [comment]
nice!

**Pull request merged**
